name: Add Prebid bidders across repos (POC)

on:
  workflow_dispatch:
    inputs:
      bidders:
        description: "Comma-separated slugs or JSON array of bidder slugs (e.g. 'kargo, teads' or ['kargo','teads'])"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  automate:
    name: Automate bidder additions (POC)
    runs-on: ubuntu-latest
    env:
      CI_GH_TOKEN: ${{ secrets.PRIVATE_GH_TOKEN != '' && secrets.PRIVATE_GH_TOKEN || github.token }}
      BASE_BRANCH: main
      BIDDERS_INPUT: ${{ inputs.bidders }}
      PREBID_REPO: al-ameen-freestar/pbjs-poc
      PUBFIG_REPO: al-ameen-freestar/pfig-poc
    steps:
      - name: Checkout AMS POC
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          # use default credential persistence

      - name: Checkout this repo (no persisted creds)
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Checkout target repo with PAT
        uses: actions/checkout@v4
        with:
          repository: ${{ env.PREBID_REPO }}
          path: Prebid.js
          token: ${{ secrets.PRIVATE_GH_TOKEN }}

      - name: Checkout pubfig POC
        uses: actions/checkout@v5
        with:
          repository: ${{ env.PUBFIG_REPO }}
          path: pubfig.js
          fetch-depth: 0
          ref: ${{ env.BASE_BRANCH }}
          token: ${{ env.CI_GH_TOKEN }}


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Authenticate gh
        run: echo "$CI_GH_TOKEN" | gh auth login --with-token

      - name: Show inputs
        run: |
          echo "BIDDERS_INPUT=$BIDDERS_INPUT"
          echo "BASE_BRANCH=$BASE_BRANCH"
          echo "PREBID_REPO=$PREBID_REPO"
          echo "PUBFIG_REPO=$PUBFIG_REPO"

      - name: Configure git to use CI token
        run: |
          git config --global url."https://${{ env.CI_GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Run automation script (updates files, creates branches, commits, pushes, opens PRs)
        run: |
          python scripts/automate_bid_adapter.py \
            --bidders "$BIDDERS_INPUT" \
            --prebid-repo "$(pwd)/Prebid.js" \
            --pubfig-repo "$(pwd)/pubfig.js" \
            --ams-repo "$(pwd)" \
            --base-branch "$BASE_BRANCH"


